Dry-run workflow
nrkno/github-workflow-semantic-release pull request #12
Opened 2022-12-02 13:08 UTC by martinsolberg

Har behov for å bruke (det kommende) versjonsnummeret i en workflow, før selve releasen utføres. Foreslår å bygge denne funksjonaliteten inn i en egen workflow.

2022-12-02 14:53 UTC, umglurf requested changes
istedenfor å lage en ny workflow er det bedre å heller legge til et nytt parameter i eksisterende `workflow.yml`, f.eks `release-dry-run` og så endre hvilken kommando som kjøres basert på den

2022-12-02 15:14 UTC, martinsolberg commented
> istedenfor å lage en ny workflow er det bedre å heller legge til et nytt parameter i eksisterende `workflow.yml`, f.eks `release-dry-run` og så endre hvilken kommando som kjøres basert på den

Vil det fungere med denne syntaksen? @umglurf

2022-12-02 15:49 UTC, umglurf commented
> > istedenfor å lage en ny workflow er det bedre å heller legge til et nytt parameter i eksisterende `workflow.yml`, f.eks `release-dry-run` og så endre hvilken kommando som kjøres basert på den
> 
> Vil det fungere med denne syntaksen? @umglurf

Det er ikke nødvendig med en hel jobb, bare å endre denne linjen: https://github.com/nrkno/github-workflow-semantic-release/pull/12#issue-1472841222
basert på om input er satt eller ikke

2022-12-05 09:06 UTC, martinsolberg commented
> > > istedenfor å lage en ny workflow er det bedre å heller legge til et nytt parameter i eksisterende `workflow.yml`, f.eks `release-dry-run` og så endre hvilken kommando som kjøres basert på den
> > 
> > 
> > Vil det fungere med denne syntaksen? @umglurf
> 
> Det er ikke nødvendig med en hel jobb, bare å endre denne linjen: [#12 (comment)](https://github.com/nrkno/github-workflow-semantic-release/pull/12#issue-1472841222) basert på om input er satt eller ikke

Den lenken funket ikke, men har endret slik jeg tror du mener nå @umglurf

2022-12-05 10:01 UTC, stigok requested changes
Du må også definere en `input` i topp for den nye variabelen du refererer til

2022-12-05 10:07 UTC, martinsolberg commented on .github/workflows/workflow.yaml
> +        if: ! ${{ inputs.dry-run }}
Oppdatert

2022-12-05 10:19 UTC, umglurf approved these changes

2022-12-05 10:55 UTC, stigok approved these changes

2022-12-05 10:58 UTC, merged