fix: set codeowners to plattform-utvikleropplevelse
nrkno/github-workflow-semantic-release pull request #28
Opened 2023-03-24 10:33 UTC by bateau84

2023-03-24 20:02 UTC, stigok requested changes
Dette er en `chore` eller `ci`, tenker jeg. Trenger ikke versionbump for dette.

2023-05-15 11:03 UTC, umglurf approved these changes

2023-05-15 12:28 UTC, merged

2023-05-15 12:29 UTC, lu-lux reviewed
okie

2023-05-15 12:29 UTC, lu-lux reviewed
okie

2023-05-15 12:29 UTC, lu-lux reviewed
okie